DROP DATABASE `ciu_futuro`;

-- MySQL Script generated by MySQL Workbench
-- Wed Sep 15 18:52:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ciu_futuro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciu_futuro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciu_futuro` DEFAULT CHARACTER SET utf8 ;
USE `ciu_futuro` ;

-- -----------------------------------------------------
-- Table `ciu_futuro`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciu_futuro`.`estado` (
  `idestado` INT NOT NULL AUTO_INCREMENT,
  `estado_construccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idestado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciu_futuro`.`materiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciu_futuro`.`materiales` (
  `construccion` VARCHAR(45) NOT NULL,
  `cemento` INT NOT NULL,
  `grava` INT NOT NULL,
  `arena` INT NOT NULL,
  `madera` INT NOT NULL,
  `abobe` INT NOT NULL,
  PRIMARY KEY (`construccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciu_futuro`.`tipo_construccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciu_futuro`.`tipo_construccion` (
  `idtipo` INT NOT NULL AUTO_INCREMENT,
  `tipo_construccion` VARCHAR(45) NULL,
  `coordenada_X` INT NULL,
  `coordenada_Y` INT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `estado` INT NOT NULL,
  `materiales_construccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`),
  INDEX `fk_tipo_construccion_estado_idx` (`estado` ASC) VISIBLE,
  INDEX `fk_tipo_construccion_materiales1_idx` (`materiales_construccion` ASC) VISIBLE,
  CONSTRAINT `fk_tipo_construccion_estado`
    FOREIGN KEY (`estado`)
    REFERENCES `ciu_futuro`.`estado` (`idestado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_construccion_materiales1`
    FOREIGN KEY (`materiales_construccion`)
    REFERENCES `ciu_futuro`.`materiales` (`construccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciu_futuro`.`materiales_usados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciu_futuro`.`materiales_usados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cemento` INT NULL,
  `grava` INT NULL,
  `arena` INT NULL,
  `madera` INT NULL,
  `adobe` INT NULL,
  `tipo_construccion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_materiales_usados_tipo_construccion1_idx` (`tipo_construccion` ASC) VISIBLE,
  CONSTRAINT `fk_materiales_usados_tipo_construccion1`
    FOREIGN KEY (`tipo_construccion`)
    REFERENCES `ciu_futuro`.`tipo_construccion` (`idtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciu_futuro`.`TIEMPO_CONSTRUCCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciu_futuro`.`TIEMPO_CONSTRUCCION` (
  `id_tiempo_construccion` VARCHAR(45) NOT NULL,
  `dias_construccion` INT NULL,
  PRIMARY KEY (`id_tiempo_construccion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO materiales (`construccion`,`cemento`,`grava`,`arena`,`madera`,`abobe`) VALUES ('CANCHA',20,20,20,20,20);
INSERT INTO materiales (`construccion`,`cemento`,`grava`,`arena`,`madera`,`abobe`) VALUES ('CASA',100,50,90,20,100);
INSERT INTO materiales (`construccion`,`cemento`,`grava`,`arena`,`madera`,`abobe`) VALUES ('EDIFICIO',200,100,180,40,200);
INSERT INTO materiales (`construccion`,`cemento`,`grava`,`arena`,`madera`,`abobe`) VALUES ('GIMNASIO',50,25,45,10,50);
INSERT INTO materiales (`construccion`,`cemento`,`grava`,`arena`,`madera`,`abobe`) VALUES ('LAGO',50,60,80,10,20);
INSERT INTO materiales (`construccion`,`cemento`,`grava`,`arena`,`madera`,`abobe`) VALUES ('INICIO_OBRA', 500, 500, 500, 500, 500);


insert into estado (estado_construccion) values ('EN PROGRESO');
insert into estado (estado_construccion) values ('PROGRAMADA');
insert into estado (estado_construccion) values ('FINALIZADA');
insert into estado (estado_construccion) values ('INICIO_OBRA');
insert into ciu_futuro.estado (estado_construccion) values ('PENDIENTE');

INSERT INTO TIEMPO_CONSTRUCCION (`id_tiempo_construccion`, `dias_construccion`) VALUES ('CASA', '3');
INSERT INTO TIEMPO_CONSTRUCCION (`id_tiempo_construccion`, `dias_construccion`) VALUES ('LAGO', '2');
INSERT INTO TIEMPO_CONSTRUCCION (`id_tiempo_construccion`, `dias_construccion`) VALUES ('CANCHA', '1');
INSERT INTO TIEMPO_CONSTRUCCION (`id_tiempo_construccion`, `dias_construccion`) VALUES ('EDIFICIO', '6');
INSERT INTO TIEMPO_CONSTRUCCION (`id_tiempo_construccion`, `dias_construccion`) VALUES ('GIMNASIO', '2');

INSERT INTO tipo_construccion 
		(tipo_construccion, coordenada_X, coordenada_Y, fecha_inicio, fecha_fin, estado,materiales_construccion)
VALUES ('INICIO_OBRA',0,0,sysdate(),DATE_ADD(SYSDATE(), INTERVAL 6 DAY),(SELECT IDESTADO FROM ciu_futuro.estado WHERE estado_construccion='INICIO_OBRA'),
		'INICIO_OBRA');
		

INSERT INTO materiales_usados 
	(`cemento`, `grava`, `arena`, `madera`, `adobe`, `tipo_construccion`) 
    VALUES ('500', '500', '500', '500', '500', (SELECT IDTIPO FROM ciu_futuro.tipo_construccion WHERE materiales_construccion='INICIO_OBRA'));


		
